Add initial test plan for media stress tests
canonical/checkbox-kivu pull request #53
Opened 2023-05-26 18:40 UTC by mckees

2023-05-26 22:20 UTC, petitfou requested changes

2023-05-26 22:20 UTC, petitfou commented on checkbox-provider-kivu/bin/gpu-load.py
> +                if "Video/" in k and (v.get("busy") is not None) and v["busy"] > threshold:
where does the variable threshold come from ?

2023-05-26 22:20 UTC, petitfou commented on checkbox-provider-kivu/bin/gpu-load.py
>              data = json.loads(content)
The semantic of the module and returned value now change a little bit depending on the argument, i would prefer an other script for that, but if we still want to keep only one file, there will be a need to document it a little bit

2023-05-26 22:20 UTC, petitfou commented on checkbox-provider-kivu/units/jobs.pxu
> +  # The stress test uses both Video/0 and Video/1, so this really checks for 24s
24s is not too hard and will make the test fail from times to times ?

2023-06-01 00:37 UTC, mckees commented
This version also has an issue with single-engine machines (My coffee lake system does not have Video/0 and Video/1, so simply dividing by two to get the time spent above the video engine utilization threshold is not a good solution. Uploading a fix for that in the next series

2023-06-01 01:04 UTC, mckees commented
@petitfou the main addition to the new patches is to add the function which counts video engines so that we don't have issues between machines that have a different number of them. If the extra code in the gpu-load script doesn't sit well with you, I can refactor out the common code like I mentioned in my inline comment above

2023-06-07 11:55 UTC, petitfou requested changes

2023-06-07 11:55 UTC, petitfou commented on checkbox-provider-kivu/units/jobs.pxu
> +  echo "{\"gpu_usage_{{ driver }}\": $(sudo ${GPU_LOAD_CMD} --timeout=30 --video_engine=Video --threshold=99.3 --gpu={{ driver }})}" | tdb.py insert &
rename gpu_usage to something elso (gpu_usage_over_threshold_duration ?)

2023-06-07 11:55 UTC, petitfou commented on checkbox-provider-kivu/units/jobs.pxu
> +_summary: Play many H264 videos (VAAPI enabled) as a stress test and capture GPU usage
Modify summary to better match the test

2023-06-07 11:55 UTC, petitfou commented on checkbox-provider-kivu/bin/gpu-thresh.py
> +        "--video_engine", type=str, help="Manually set the video engine you" \
you can use choices=['Video', 'VideoEnhance'], default='Video' , with that, you will be able to remove the check later on ...

2023-06-07 11:55 UTC, petitfou commented on checkbox-provider-kivu/bin/gpu-thresh.py
> +    if args.video_engine is None:
... here , juste have to do : video_engine = f'{args.video_engine}/'

2023-06-07 20:54 UTC, petitfou approved these changes
LGTM +1

2023-06-07 21:18 UTC, mckees commented
@petitfou I don't have merge rights. Could you please merge for me?

2023-06-07 22:15 UTC, merged